name: volco
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.1+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  pdf: ^3.10.4
  printing: ^5.12.0
  google_fonts: ^6.1.0
  flutter_speed_dial: ^7.0.0
  flutter_colorpicker: ^1.0.3
  file_picker: ^10.0.2
  share_plus: ^11.0.0
  uuid: ^4.0.0
  supabase_flutter: ^2.9.1
  app_links: ^6.4.0
  dio: ^5.4.0
  permission_handler: ^11.3.0
  open_filex: ^4.1.1
  connectivity_plus: ^5.0.2
  http: ^1.2.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/logo_volco.png
    - assets/imgs/logo_volqueta.png
    - assets/imgs/fondo.png
    - assets/fonts/BebasNeue-Regular.ttf
    - assets/fonts/Inter-Regular.ttf
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo_volco.png"