"""Add service_account_id to invoice_customizations

Revision ID: 1e738d1216d2
Revises: 015a590bb691
Create Date: 2026-03-03 21:14:33.913772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e738d1216d2'
down_revision: Union[str, Sequence[str], None] = '015a590bb691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_customizations', sa.Column('service_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoice_customizations_service_account_id'), 'invoice_customizations', ['service_account_id'], unique=False)
    op.create_foreign_key(None, 'invoice_customizations', 'service_accounts', ['service_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_customizations', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_customizations_service_account_id'), table_name='invoice_customizations')
    op.drop_column('invoice_customizations', 'service_account_id')
    # ### end Alembic commands ###
