"""Update heartbeat table

Revision ID: 2b20eb5f16b9
Revises: b14d1aba085f
Create Date: 2025-12-04 19:55:00.894446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b20eb5f16b9'
down_revision: Union[str, Sequence[str], None] = 'b14d1aba085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeat', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heartbeat', 'updated_at')
    # ### end Alembic commands ###
