"""rename table service to services

Revision ID: 6cf8c3c92edc
Revises: a1573b632775
Create Date: 2025-11-22 19:31:58.346791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cf8c3c92edc'
down_revision: Union[str, Sequence[str], None] = 'a1573b632775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('custom_material', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('service_account_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_material_id'), 'services', ['material_id'], unique=False)
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_index(op.f('ix_service_material_id'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('service_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('service_material_id_fkey')),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], name=op.f('service_service_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pkey'))
    )
    op.create_index(op.f('ix_service_material_id'), 'service', ['material_id'], unique=False)
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.drop_index(op.f('ix_services_material_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
