"""initial schema

Revision ID: a1573b632775
Revises: 
Create Date: 2025-11-22 19:26:30.522933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1573b632775'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_username'), 'providers', ['username'], unique=True)
    op.create_table('clients',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_provider_id'), 'clients', ['provider_id'], unique=False)
    op.create_table('invoice_customizations',
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_bank', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_type_account', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_number_account', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('service_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('footer_message', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('apply_to_all_accounts', sa.Boolean(), nullable=False),
    sa.Column('include_logo', sa.Boolean(), nullable=False),
    sa.Column('include_signature', sa.Boolean(), nullable=False),
    sa.Column('include_footer', sa.Boolean(), nullable=False),
    sa.Column('include_banck_info', sa.Boolean(), nullable=False),
    sa.Column('page_size', sa.Enum('A4', 'LETTER', 'LEGAL', name='pagesizes'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_customizations_id'), 'invoice_customizations', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_customizations_provider_id'), 'invoice_customizations', ['provider_id'], unique=False)
    op.create_table('materials',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_provider_id'), 'materials', ['provider_id'], unique=False)
    op.create_table('service_accounts',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_accounts_client_id'), 'service_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_service_accounts_id'), 'service_accounts', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('service_account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_provider_id'), 'invoices', ['provider_id'], unique=False)
    op.create_index(op.f('ix_invoices_service_account_id'), 'invoices', ['service_account_id'], unique=True)
    op.create_table('service',
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('custom_material', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('service_account_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_material_id'), 'service', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_material_id'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_invoices_service_account_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_provider_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_service_accounts_id'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_client_id'), table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index(op.f('ix_materials_provider_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_invoice_customizations_provider_id'), table_name='invoice_customizations')
    op.drop_index(op.f('ix_invoice_customizations_id'), table_name='invoice_customizations')
    op.drop_table('invoice_customizations')
    op.drop_index(op.f('ix_clients_provider_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_providers_username'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
