"""Update invoice table

Revision ID: b14d1aba085f
Revises: 6a6eeb708985
Create Date: 2025-12-04 19:41:16.857652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b14d1aba085f'
down_revision: Union[str, Sequence[str], None] = '6a6eeb708985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'end_date')
    op.drop_column('invoices', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
