"""Update heartbeat table

Revision ID: bb2ffbb4d14d
Revises: ed42bd8d4f86
Create Date: 2025-11-23 02:34:43.257577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb2ffbb4d14d'
down_revision: Union[str, Sequence[str], None] = 'ed42bd8d4f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeat_id'), table_name='heartbeat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_heartbeat_id'), 'heartbeat', ['id'], unique=False)
    # ### end Alembic commands ###
